### ISSUE TITLE
win10下为什么调用不了

### ISSUE THREAD

**Issue by sexfio** [xulihang/WinRTOCR#1]
未经处理的异常:Systen.TpeLoadException:找不到windows运行时类型“Windows.Globalization . Language。>s9ste"-r -
uage"。---> system.PlatfornNotsupportedException:此平台上不支
持操作。
内部异常堆栈跟踪的结尾——-inRTOCR.Program.<Main >d_.MoueNext《>
在Systen.Runtime .Compiler8ervices.AsyncTaskMethodBuilder.Start[TStateMachine1<TStateMachine&stateMachine>
在inRTOCR.Program.Main<Stringl ]args>在winRTOCR.Program .<Main><Stringt i args >

**Comment by xulihang** [comment]
你是自己编译的吗，我在几个Windows10上测试都没碰到问题
