### ISSUE TITLE
无法识别其他语言

### ISSUE THREAD

**Issue by Isayama-Kagura** [xulihang/WinRTOCR#2]
好像只能使用默认的语言进行识别

![image](https://user-images.githubusercontent.com/30114848/189489958-eb511f20-ffa9-492b-b96b-c37a977afeab.png)

**Comment by xulihang** [comment]
具体用法可以参考这个ImageTrans的插件：https://github.com/xulihang/ImageTrans_plugins/blob/master/WinRTOCR/WinRTOCRPlugin.bas
